package libPack;
// *****************************************************************.
// This file (ConfigText.java) can be recreated via the application genConfig.
// Edits to this file will be lost when genConfig is run and the resulting
// ConfigText.java is copied to genLables libPack.
// *****************************************************************.

import fileWork.FileWork;

import java.util.ArrayList;

// A default (DENVER) BulletinAssembly genLabels configuration file.
// This class will create a new necessary default (DENVER) config.xml.
public class ConfigText
{
   public ConfigText(Shared shared)
   {
      this.shared = shared;
   }
   private Shared shared = null;

   public String writeConfigText() throws InternalFatalError
   {
      FileWork fileWork = shared.getFileWork();
      String configFilePathName = shared.getConfigFilePathName();

      ArrayList<String> configStrAL = createConfigStrAL();
      try
      {
         fileWork.writeFile(configFilePathName, configStrAL);
      }
      catch (InternalFatalError exct)
      {
         throw new InternalFatalError();
      }

      return configFilePathName;
   }


   public ArrayList<String> createConfigStrAL()
   {
      ArrayList<String> configStrAL = new ArrayList<String>();

      configStrAL.add("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
      configStrAL.add("<!-- -->");
      configStrAL.add("<!-- BulletinSlicer Configuration File -->");
      configStrAL.add("<!-- -->");
      configStrAL.add("<!-- -->");
      configStrAL.add("<!-- -->");
      configStrAL.add("<!-- ***************  Revision History (begun 140921) *************** -->");
      configStrAL.add("<!-- 210316 correct omx and Zones (THIS HAS NOT BEEN KEPT UP TO DATE!!-->");
      configStrAL.add("<!-- 180223 correct omx and Zones -->");
      configStrAL.add("<!-- 1710 correct omx, and Zones -->");
      configStrAL.add("<!-- Others prior to this... not recored -->");
      configStrAL.add("<!-- 160319 Corrected: omx, DACD, SCF and Zones (few changes) -->");
      configStrAL.add("<!-- 150903 Corrected: omx, DACD, SCF and Zones ... all needed changes -->");
      configStrAL.add("<!-- 150126 Corrected: omx, check SCF and check zones .. they were ok -->");
      configStrAL.add("<!-- 14/09/04 Corrected: DEN_SCF, DEN_ADC, ZONE[1to9] -->");
      configStrAL.add("<!-- **************************************************************** -->");
      configStrAL.add("<ROOT>");
      configStrAL.add("  <!-- ************************************************************************** -->");
      configStrAL.add("  <!-- -->");
      configStrAL.add("  <!-- The primary Elements:-->");
      configStrAL.add("  <!--    Element: RANGES are definitions of zip codes per tray.-->");
      configStrAL.add("  <!--    Element: OMX (under RANGES) is the most likely range to suffer change, hence is broken into pieces.-->");
      configStrAL.add("  <!--             Find OMX at http://pe.usps.com/text/dmm300/L201.htm -->");
      configStrAL.add("  <!--    Element: IC (under RANGES) is not likely to change.  But is defined as OMX to ease of codeing.-->");
      configStrAL.add("  <!--    Element: USPSPRIORITY are USPS priorities.  The USPS will sort and distribute trays in this order.-->");
      configStrAL.add("  <!--    Element: SLICEORDER is our priorities.  The order BuilitenSlicer will slice labels. The order the-->");
      configStrAL.add("  <!--             Check list will be generated.  The order the Trays will be packed.-->");
      configStrAL.add("  <!--    Element: ZONES is the USPS list of zones with their assigned zip code for shipment from 802-->");
      configStrAL.add("  <!--             Find Zones at http://postcalc.usps.com/ZoneChart and enter 802-->");
      configStrAL.add("  <!--             I have written ZoneTxtToXML.  Cut and paste the content of the html file into-->");
      configStrAL.add("  <!--             a text file.  ZoneTxtToXML will convert that to XML format useful in this file.-->");
      configStrAL.add("  <!--    Element: ZIPCOUNTS is used to find the zip codes columns listed in each zone formual set.-->");
      configStrAL.add("  <!--             It is used when one checks for errors in Excel sheet ZipCounts.-->");
      configStrAL.add("  <!--    Element: ADDRESSLIST is used to verify the user\'s selected AddressList.csv file via headers and-->");
      configStrAL.add("  <!--             zip codes in the \"Zip\" Column, and to find the \"Zip\" and \"Renewal\" columns.-->");
      configStrAL.add("  <!-- -->");
      configStrAL.add("  <!-- You can edit this file in any text editor.  But be careful.  A damaged file may break BulletinSlicer.-->");
      configStrAL.add("  <!-- Stick to the existing Element format.  Do not add Elements.  If you break this XML file, delete it-->");
      configStrAL.add("  <!-- and let BulletinSlicer create a new default file. (Defined for the Denver, Colorado 802 zone.-->");
      configStrAL.add("  <!-- -->");
      configStrAL.add("  <!-- Some Do\'s and Don\'ts-->");
      configStrAL.add("  <!-- -->");
      configStrAL.add("  <!--    DOs-->");
      configStrAL.add("  <!--       DO CHANGE zips codes and zip ranges to remain current with USPS updates/changes.-->");
      configStrAL.add("  <!--           Example:  OK to change 807-812 to 807-809, 811-812 if 810 was moved by the USPS.-->");
      configStrAL.add("  <!-- -->");
      configStrAL.add("  <!--    DON\'Ts-->");
      configStrAL.add("  <!--       In general:  DO NOT delete any element.  DO NOT change the spelling of any element.-->");
      configStrAL.add("  <!--           Example:  Do not change \"DADC\" to \"ADC\".-->");
      configStrAL.add("  <!--       DO NOT delete a RANGE-->");
      configStrAL.add("  <!--           Example:  The code uses \'STATE\', if deleted it would cause a problem-->");
      configStrAL.add("  <!-- -->");
      configStrAL.add("  <!--       But there are always exceptions to the general rule.-->");
      configStrAL.add("  <!--       Most often you can change the order of sub elements.-->");
      configStrAL.add("  <!--       In RANGES: One could add a new SCF if the USPS were to create one.-->");
      configStrAL.add("  <!--           One can change \"DEN_SCF\" to \"NYC_SCF\"; but don\'t change the \"_SCF\".-->");
      configStrAL.add("  <!--           But your stuck with the other RANGES elements.  If the USPS were to add \"DDS\",-->");
      configStrAL.add("  <!--           you could not create a matching \"DDS\" Element without a code change.-->");
      configStrAL.add("  <!--       In RANGES/OMX or IC you can add or delete any \"omx\" or \"ic\" elements as necessary-->");
      configStrAL.add("  <!-- -->");
      configStrAL.add("  <!-- ************************************************************************** -->");
      configStrAL.add("  <!-- 170923 following works to find Lxxx\'s MXD, OMX, SCF, ADC -->");
      configStrAL.add("  <!-- (Is subject to change by the whim of the USPS.) -->");
      configStrAL.add("  <!-- http://pe.usps.com -->");
      configStrAL.add("  <!--    Click:  Quick Service Guide -->");
      configStrAL.add("  <!--    Click: 207d Periodicals Nonbarcode Flats -->");
      configStrAL.add("  <!--    Scroll down to ditrution diagram -->");
      configStrAL.add("  <!--    Click on any Lxxx within a sequence -->");
      configStrAL.add("  <!--       OMX L201 -->");
      configStrAL.add("  <!--    Further... Scroll down to 800 Denver for list of zip codes  -->");
      configStrAL.add("  <!--    Find Zones at https://postcalc.usps.com/DomesticZoneChart and enter 802 -->");
      configStrAL.add("  <!-- ************************************************************************** -->");
      configStrAL.add("  <!-- The USPS web sites must be checked periodically to insure this file is up to date. -->");
      configStrAL.add("  <!-- (Some USPS web site addresses (subject to change) are noted in the header comments.) -->");
      configStrAL.add("  <!-- The date format is: mm/dd/yyyy (12/3/2014) -->");
      configStrAL.add("  <!--  -->");
      configStrAL.add("  <!-- SEE HELP JUST ABOVE THIS -->");
      configStrAL.add("  <!-- Element DateReminder:  Manually set approxamently 3 months in the future -->");
      configStrAL.add("  <!-- Element ReminderUpdated:  The date one did updates from the UPS -->");
      configStrAL.add("  <!--  -->");
      configStrAL.add("  <DATEREMINDER>");
      configStrAL.add("    <DateReminder>03/01/2022</DateReminder>");
      configStrAL.add("    <LastDataCorrection>12/10/2021</LastDataCorrection>");
      configStrAL.add("    <ReminderUpdated>12/10/2021</ReminderUpdated>");
      configStrAL.add("  </DATEREMINDER>");
      configStrAL.add("  <!-- ************************************************************************** -->");
      configStrAL.add("  <LABELSACROSS>");
      configStrAL.add("    <LabelsAcross>3</LabelsAcross>");
      configStrAL.add("  </LABELSACROSS>");
      configStrAL.add("  <MINTRAYCNT>");
      configStrAL.add("    <MinTrayCnt>24</MinTrayCnt>");
      configStrAL.add("  </MINTRAYCNT>");
      configStrAL.add("  <!-- ************************************************************************** -->");
      configStrAL.add("  <!-- USPS Tray labels -->");
      configStrAL.add("  <!-- RANGES (my mnemonic) are very much like a \"local zone\". -->");
      configStrAL.add("  <!-- DADC: \"Destination Area Distribution Center\". (Lending \"D\" is NOT \"Denver\".) (L004) -->");
      configStrAL.add("  <!-- SCF: \"Sectional Center Facility\"  (L005) -->");
      configStrAL.add("  <!-- OMX: \"Origin Mixed ADC\"  (Area Distribution Center) (L201) -->");
      configStrAL.add("  <!-- IC: \"In Counting\" (my mnemonic) I got the IC list from Tom Umland of the USPS. -->");
      configStrAL.add("  <!--       (There isn\'t a tray label \"IC\".) -->");
      configStrAL.add("  <RANGES>");
      configStrAL.add("    <!-- Last update 211210 -->");
      configStrAL.add("    <!--       (L002 for SCF\'s, L004 for ADC) -->");
      configStrAL.add("    <!-- TODO need a Boulder SCF in BulletinSlicer 813, Longmont 805, Colorado Springs 808, 809, 810 -->");
      configStrAL.add("    <!-- TODO need STATE to accept 800-812,814-816 so as to exclude 813 -->");
      configStrAL.add("    <!-- 813 is Aluquerque NM -->");
      configStrAL.add("    <STATE>800-816</STATE>");
      configStrAL.add("    <!-- CS_SCF is DEN_SCF... USPS combined CS_SCF into DEN_SCF. -->");
      configStrAL.add("    <!-- ............................................................... -->");
      configStrAL.add("    <!-- PROBLEM. Due to lack my of experience with XML: when I desiged -->");
      configStrAL.add("    <!-- this xml config file I made it to specific. It is locked to Denver -->");
      configStrAL.add("    <!-- Elsewhere there may be multiple SCF\'s or even ADC\'s.  But the -->");
      configStrAL.add("    <!-- software (due to the poor design of the xml file) is hard coded to -->");
      configStrAL.add("    <!-- these Denver specfic:  DEN_SCF, GJ_SCF and DADC -->");
      configStrAL.add("    <!-- If ever used elsewhere (unlikely) the code will have to be fixed -->");
      configStrAL.add("    <!-- ............................................................... -->");
      configStrAL.add("    <!-- In dapa I ignore GJ_SCF as there is no change it will ever -->");
      configStrAL.add("    <!-- justify a full tray. -->");
      configStrAL.add("    <!-- USPS combined CS_SCF into DEN_SCF (late 2018 or 17). -->");
      configStrAL.add("    <!-- 191214 CS_SCF is 808 and 810 ... have left combined in DEN_SCF -->");
      configStrAL.add("    <DEN_SCF>800-812</DEN_SCF>");
      configStrAL.add("    <GJ_SCF>814-816</GJ_SCF>");
      configStrAL.add("    <DADC>800-812</DADC>");
      configStrAL.add("    <!-- I do not know of any web address to get this data from. -->");
      configStrAL.add("    <!-- I got it many years ago from the clerk Thomas Umland, who give me an unofficial -->");
      configStrAL.add("    <!-- sheet of paper, and has since retired. -->");
      configStrAL.add("    <!-- through my intire tenure it has not been challanged or modified -->");
      configStrAL.add("    <IC>");
      configStrAL.add("      <ic>80201</ic>");
      configStrAL.add("      <ic>80202</ic>");
      configStrAL.add("      <ic>80203</ic>");
      configStrAL.add("      <ic>80204</ic>");
      configStrAL.add("      <ic>80205</ic>");
      configStrAL.add("      <ic>80206</ic>");
      configStrAL.add("      <ic>80207</ic>");
      configStrAL.add("      <ic>80208</ic>");
      configStrAL.add("      <ic>80209</ic>");
      configStrAL.add("      <ic>80210</ic>");
      configStrAL.add("      <ic>80211</ic>");
      configStrAL.add("      <ic>80212</ic>");
      configStrAL.add("      <ic>80213</ic>");
      configStrAL.add("      <ic>80216</ic>");
      configStrAL.add("      <ic>80217</ic>");
      configStrAL.add("      <ic>80218</ic>");
      configStrAL.add("      <ic>80219</ic>");
      configStrAL.add("      <ic>80220</ic>");
      configStrAL.add("      <ic>80222</ic>");
      configStrAL.add("      <ic>80223</ic>");
      configStrAL.add("      <ic>80224</ic>");
      configStrAL.add("      <ic>80230</ic>");
      configStrAL.add("      <ic>80231</ic>");
      configStrAL.add("      <ic>80232</ic>");
      configStrAL.add("      <ic>80235</ic>");
      configStrAL.add("      <ic>80236</ic>");
      configStrAL.add("      <ic>80237</ic>");
      configStrAL.add("      <ic>80238</ic>");
      configStrAL.add("      <ic>80239</ic>");
      configStrAL.add("      <ic>80242</ic>");
      configStrAL.add("      <ic>80243</ic>");
      configStrAL.add("      <ic>80244</ic>");
      configStrAL.add("      <ic>80245</ic>");
      configStrAL.add("      <ic>80246</ic>");
      configStrAL.add("      <ic>80247</ic>");
      configStrAL.add("      <ic>80249</ic>");
      configStrAL.add("      <ic>80250</ic>");
      configStrAL.add("    </IC>");
      configStrAL.add("    <!-- OMX Last Update 211210 (L201) -->");
      configStrAL.add("<OMX>");
      configStrAL.add("  <omx>090-099</omx>");
      configStrAL.add("  <omx>375</omx>");
      configStrAL.add("  <omx>380-383</omx>");
      configStrAL.add("  <omx>386</omx>");
      configStrAL.add("  <omx>388</omx>");
      configStrAL.add("  <omx>400-406</omx>");
      configStrAL.add("  <omx>410</omx>");
      configStrAL.add("  <omx>413-414</omx>");
      configStrAL.add("  <omx>427</omx>");
      configStrAL.add("  <omx>430-433</omx>");
      configStrAL.add("  <omx>437-438</omx>");
      configStrAL.add("  <omx>450-452</omx>");
      configStrAL.add("  <omx>456-474</omx>");
      configStrAL.add("  <omx>478-479</omx>");
      configStrAL.add("  <omx>488-491</omx>");
      configStrAL.add("  <omx>493-495</omx>");
      configStrAL.add("  <omx>498-516</omx>");
      configStrAL.add("  <omx>520-528</omx>");
      configStrAL.add("  <omx>530-532</omx>");
      configStrAL.add("  <omx>534-535</omx>");
      configStrAL.add("  <omx>537-551</omx>");
      configStrAL.add("  <omx>553-564</omx>");
      configStrAL.add("  <omx>566</omx>");
      configStrAL.add("  <omx>570-575</omx>");
      configStrAL.add("  <omx>577</omx>");
      configStrAL.add("  <omx>590-620</omx>");
      configStrAL.add("  <omx>622-631</omx>");
      configStrAL.add("  <omx>633-641</omx>");
      configStrAL.add("  <omx>644-647</omx>");
      configStrAL.add("  <omx>649-653</omx>");
      configStrAL.add("  <omx>660-662</omx>");
      configStrAL.add("  <omx>664-681</omx>");
      configStrAL.add("  <omx>683-693</omx>");
      configStrAL.add("  <omx>710-714</omx>");
      configStrAL.add("  <omx>716-731</omx>");
      configStrAL.add("  <omx>733-741</omx>");
      configStrAL.add("  <omx>743-770</omx>");
      configStrAL.add("  <omx>772-784</omx>");
      configStrAL.add("  <omx>786-816</omx>");
      configStrAL.add("  <omx>820-838</omx>");
      configStrAL.add("  <omx>840-847</omx>");
      configStrAL.add("  <omx>850-853</omx>");
      configStrAL.add("  <omx>855-857</omx>");
      configStrAL.add("  <omx>859-860</omx>");
      configStrAL.add("  <omx>863-865</omx>");
      configStrAL.add("  <omx>870-871</omx>");
      configStrAL.add("  <omx>873-885</omx>");
      configStrAL.add("  <omx>889-891</omx>");
      configStrAL.add("  <omx>893-895</omx>");
      configStrAL.add("  <omx>897-898</omx>");
      configStrAL.add("  <omx>900-908</omx>");
      configStrAL.add("  <omx>910-928</omx>");
      configStrAL.add("  <omx>930-935</omx>");
      configStrAL.add("  <omx>942</omx>");
      configStrAL.add("  <omx>952-953</omx>");
      configStrAL.add("  <omx>956-961</omx>");
      configStrAL.add("  <omx>979-985</omx>");
      configStrAL.add("  <omx>988</omx>");
      configStrAL.add("  <omx>990-994</omx>");
      configStrAL.add("</OMX>");
      configStrAL.add("  </RANGES>");
      configStrAL.add("  <!-- ************************************************************************** -->");
      configStrAL.add("  <!-- The USPS distribution priority. -->");
      configStrAL.add("  <!-- Higher level priorities will be handled more quickly at less cost. -->");
      configStrAL.add("  <!-- DO NOT add any elements, or change the spelling of any element. -->");
      configStrAL.add("  <!-- If the USPS changes their priority order, you can change the order. -->");
      configStrAL.add("  <USPSPRIORITY>");
      configStrAL.add("    <PRIORITIES>");
      configStrAL.add("      <priority>D5</priority>");
      configStrAL.add("      <priority>D3</priority>");
      configStrAL.add("      <priority>SCF</priority>");
      configStrAL.add("      <priority>DADC</priority>");
      configStrAL.add("      <priority>OMX</priority>");
      configStrAL.add("      <priority>MXD</priority>");
      configStrAL.add("    </PRIORITIES>");
      configStrAL.add("  </USPSPRIORITY>");
      configStrAL.add("  <!-- ************************************************************************** -->");
      configStrAL.add("  <!-- Slice Order address labels by tray. -->");
      configStrAL.add("  <!-- Use these elements to change the order labels are created, -->");
      configStrAL.add("  <!-- and the order of the Check List used on assembly night. -->");
      configStrAL.add("  <!-- You CAN NOT add new elements or change the spelling of existing values. -->");
      configStrAL.add("  <!-- Side Comment: -->");
      configStrAL.add("  <!--    I put D5 first as it is the simplest.  Then MXD, OMX to get them out of -->");
      configStrAL.add("  <!--    the way quickly, as they small.  Then DADC and SCF, as they contain few -->");
      configStrAL.add("  <!--    multiple 5D zip sets.  Hence, they are more difficult to label and check off. -->");
      configStrAL.add("  <!--    Finally D3 with many multiple 5D zip set and where the bulk of the isses are. -->");
      configStrAL.add("    <!-- D5 no longer exists... 80228 use to have 25+ subscribers... no more.  -->");
      configStrAL.add("  <SLICEORDER>");
      configStrAL.add("    <ORDERS>");
      configStrAL.add("      <order>D5</order>");
      configStrAL.add("      <order>MXD</order>");
      configStrAL.add("      <order>OMX</order>");
      configStrAL.add("      <order>DADC</order>");
      configStrAL.add("      <order>SCF</order>");
      configStrAL.add("      <order>D3</order>");
      configStrAL.add("    </ORDERS>");
      configStrAL.add("  </SLICEORDER>");
      configStrAL.add("  <!-- ************************************************************************** -->");
      configStrAL.add("  <!-- Zones:  is used by BulletinSlicer to generate a Zip Codes per Zone Report, -->");
      configStrAL.add("  <!-- and, also to ZipCheck sheet ZipCount zones.-->");
      configStrAL.add("  <!--    Find Zones at https://postcalc.usps.com/DomesticZoneChart and enter 802 -->");
      configStrAL.add("  <!--  -->  ");
      configStrAL.add("  <!--    BulletinSlicer has a check box to convert the cut and paste copy of the html file onto -->");
      configStrAL.add("  <!--    the clipboard in XML format suitable to paste here. -->");
      configStrAL.add("  <!-- You CAN NOT add new elements.  You can update the 3 Digit zip codes pre USPS changes. -->");
      configStrAL.add("  <!-- (Should be checked every few months. -->");
      configStrAL.add("  <!--     I left it lay unchanged for to long and there were many differences between old and new.  -->");
      configStrAL.add("  <!-- Luckly only 3 zips found in ZipCounts, and none of those with a item count. ) -->");
      configStrAL.add("  <!-- -->");
      configStrAL.add("  <!-- Last update 221210 -->");
      configStrAL.add("  <ZONES>");
      configStrAL.add("    <ZONE1>800-812</ZONE1>");
      configStrAL.add("    <ZONE2>808-810, 820, 822-823</ZONE2>");
      configStrAL.add("    <ZONE3>577, 677, 690-693, 814-816, 824-828</ZONE3>");
      configStrAL.add("    <ZONE4>500-503, 505, 508-516, 525, 570-576, 585-588, 590-597, 640-641, 644-647, 649, 660-662, 664-676, 678-681, 683-689, 730-731, 734-741, 743-749, 768-769, 790-799, 813, 821, 829-832, 834, 840-847, 850-853, 855-857, 859-860, 863, 865, 870-871, 873-885, 898</ZONE4>");
      configStrAL.add("    <ZONE5>369-372, 375, 380-393, 396-397, 420-424, 460-466, 469, 472, 474-479, 490-491, 493-495, 498-499, 504, 506-507, 520-524, 526-528, 530-532, 534-535, 537-551, 553-567, 580-584, 598-620, 622-631, 633-639, 648, 650-658, 705-708, 710-714, 716-729, 733, 750-767, 770, 772-789, 833, 835-838, 864, 889-891, 893-895, 897, 900-908, 910-928, 930-954, 956-961, 962-966, 970-979, 983-986, 988-994</ZONE5>");
      configStrAL.add("    <ZONE6>140-168, 240-243, 245-253, 255-266, 270-274, 280-282, 286-293, 295-298, 300-312, 316-319, 323-325, 350-352, 354-368, 373-374, 376-379, 394-395, 398-418, 425-427, 430-459, 467-468, 470-471, 473, 480-489, 492, 496-497, 700-701, 703-704, 955, 980-982</ZONE6>");
      configStrAL.add("    <ZONE7>005, 010-043, 045, 048, 050-089, 090-099, 100-139, 169-212, 214-239, 244, 254, 267-268, 275-279, 283-285, 294, 299, 313-315, 320-322, 326-342, 344, 346-347, 349, 999</ZONE7>");
      configStrAL.add("    <ZONE8>006-009, 044, 046-047, 049, 967-968, 995-998</ZONE8>");
      configStrAL.add("  </ZONES>");
      configStrAL.add("  <!-- ************************************************************************** -->");
      configStrAL.add("  <!--Excel Sheet ZipCounts Zone names and Excel column name -->");
      configStrAL.add("  <!--The column specified is the column containing 5 digit zip codes. -->");
      configStrAL.add("  <!--For each zone.  These elements are used for titles in Zip Checks. -->");
      configStrAL.add("  <ZIPCOUNTS>");
      configStrAL.add("    <IC>V</IC>");
      configStrAL.add("    <DEN_SCF>AJ</DEN_SCF>");
      configStrAL.add("    <DADC>AX</DADC>");
      configStrAL.add("    <ZONE2>BK</ZONE2>");
      configStrAL.add("    <ZONE3>BV</ZONE3>");
      configStrAL.add("    <ZONE4>CG</ZONE4>");
      configStrAL.add("    <ZONE5>CR</ZONE5>");
      configStrAL.add("    <ZONE6>DC</ZONE6>");
      configStrAL.add("    <ZONE7>DN</ZONE7>");
      configStrAL.add("    <ZONE8>DY</ZONE8>");
      configStrAL.add("  </ZIPCOUNTS>");
      configStrAL.add("  <!-- ************************************************************************** -->");
      configStrAL.add("  <!--Excel Sheet ZipCodes Excel column name -->");
      configStrAL.add("  <!--The column specified is the column containing 5 digit zip codes. -->");
      configStrAL.add("  <!--For each zone.  These elements are used for to verify the data -->");
      configStrAL.add("  <!--genZipCodes only uses the Zip column -->");
      configStrAL.add("  <ZIPCODES>");
      configStrAL.add("    <ZIP>A</ZIP>");
      configStrAL.add("    <PIECES>B</PIECES>");
      configStrAL.add("    <CHK>C</CHK>");
      configStrAL.add("    <TRAY>D</TRAY>");
      configStrAL.add("  </ZIPCODES>");
      configStrAL.add("  <!-- ************************************************************************** -->");
      configStrAL.add("  <!--Excel Sheet AddressList headers and columns -->");
      configStrAL.add("  <!--Used to find the \"Zip\", \"Plus 4\" and \"Renewal\" columns. -->");
      configStrAL.add("  <!--And to verify the AddressList.csv file via the \"Zip\" and \"Plus 4\" columns. -->");
      configStrAL.add("  <!--BulletinSlicer EXPECTS Zip to be the 7th item and Plus 4 to be the 8th (array members [6] & [7]) -->");
      configStrAL.add("  <ADDRESSLIST>");
      configStrAL.add("    <LastName>A</LastName>");
      configStrAL.add("    <FirstName>B</FirstName>");
      configStrAL.add("    <OtherName>C</OtherName>");
      configStrAL.add("    <Address>D</Address>");
      configStrAL.add("    <City>E</City>");
      configStrAL.add("    <State>F</State>");
      configStrAL.add("    <Zip>G</Zip>");
      configStrAL.add("    <Plus4>H</Plus4>");
      configStrAL.add("    <Renewal>J</Renewal>");
      configStrAL.add("  </ADDRESSLIST>");
      configStrAL.add("  <!-- Excel Sheet AddressList headers -->");
      configStrAL.add("  <!-- Used to Verify that the CSV file\'s row 1 is an Excel Header Line -->");
      configStrAL.add("  <!-- These EXACT SPELLINGS must be in the columns listed above as the content of row 1. -->");
      configStrAL.add("  <!-- BulletinSlicer EXPECTS Zip to be the 7th item and Plus 4 to be the 8th (array members [6] & [7]) -->");
      configStrAL.add("  <MAILMERGEHEADER>");
      configStrAL.add("    <LastName>Lname</LastName>");
      configStrAL.add("    <FirstName>Fname</FirstName>");
      configStrAL.add("    <OtherName>Company</OtherName>");
      configStrAL.add("    <Address>Address</Address>");
      configStrAL.add("    <City>City</City>");
      configStrAL.add("    <State>State</State>");
      configStrAL.add("    <Zip>Zip</Zip>");
      configStrAL.add("    <Plus4>Plus 4</Plus4>");
      configStrAL.add("    <Renewal>Renewal</Renewal>");
      configStrAL.add("  </MAILMERGEHEADER>");
      configStrAL.add("  <!-- ************************************************************************** -->");
      configStrAL.add("  <!-- Define which excel column should appear on which line (1-5) of address labels -->");
      configStrAL.add("  <!-- Currently:  J==Renewal, B==Fname, C==Company, D==Address, E==City -->");
      configStrAL.add("  <LABELLINES>");
      configStrAL.add("    <Line1Column>J</Line1Column>");
      configStrAL.add("    <Line2Column>B</Line2Column>");
      configStrAL.add("    <Line3Column>C</Line3Column>");
      configStrAL.add("    <Line4Column>D</Line4Column>");
      configStrAL.add("    <Line5Column>E</Line5Column>");
      configStrAL.add("  </LABELLINES>");
      configStrAL.add("</ROOT>");
      configStrAL.add("");
      configStrAL.add("");
      configStrAL.add("");
      configStrAL.add("");

      return configStrAL;
   }
}

